### ISSUE TITLE
[FEAT] Launch datepicker from input field

### ISSUE THREAD

**Issue by ryananthonydrake** [SimeonC/sc-date-time#10]
Would be great to launch the datepicker on a popup when an input field is clicked on, with placeholder values, and once 'Save' is clicked, the date/time value is then represented in the input field.

Super useful for check in/check out forms!

**Comment by SimeonC** [comment]
This kind of demo will be done in #6. Actually integrating this into the plugin itself is something I'd rather avoid - just to keep the implementation simpler and dependencies down as this supports Bootstrap and Material.
