### ISSUE TITLE
please don't force font-awesome

### ISSUE THREAD

**Issue by seiyria** [SimeonC/sc-date-time#11]
As much as I like font awesome, using angular/material all of my icons are in a different icon set completely. I don't want to pull in font awesome just for this library and I probably won't use it as a result.

**Comment by SimeonC** [comment]
Font-awesome isn't forced, it's just the default. If you want to use something else just override the templates or create a new one. Templates are named `scDateTime-#{tAttrs.theme}.tpl` and then whatever you pass as the theme attribute or the defaultTheme value in the config selects it. This way you can define your own template to use your own icons.

Thanks,
~Simeon

Sent from my iPhone

**Comment by seiyria** [comment]
That's about what I would have expected. Is this documented anywhere?

**Comment by SimeonC** [comment]
Apparently not clearly enough. The theme options are but not about the ability to create your own. I'll add it into the read me and site later today.
