### ISSUE TITLE
Failed to load template: scDateTime-material.tpl (HTTP status: 404 Not Found)

### ISSUE THREAD

**Issue by mrcel** [SimeonC/sc-date-time#12]
Where can I find the tpl file?

**Comment by SimeonC** [comment]
It should be automatically loaded as part of the js file here: https://github.com/SimeonC/sc-date-time/blob/master/dist/sc-date-time.js#L362.

I have also compiled the tpl files into the dist folder if you are using it differently. Let me know if that solves your problem.
