### ISSUE TITLE
Months with 6 weeks are not handled gracefully

### ISSUE THREAD

**Issue by rfuhrer** [SimeonC/sc-date-time#14]
![image](https://cloud.githubusercontent.com/assets/2529744/10323143/565aacfc-6c3e-11e5-8b2c-bfba8f213124.png)

I'll submit a pull request if I find a nice fix, but I thought I'd bring this up in case you had some time to work on it.

Thanks!

**Comment by SimeonC** [comment]
Hmmm, I think there may be some conflicting stylesheets going on there - I can't spot that here: http://simeonc.github.io/sc-date-time/material.html. Can you show run up a plunkr or similar showing the problem?

**Comment by rfuhrer** [comment]
hmm.. interesting.  Maybe there's a new version of chrome that's messing everything up? I'm running Version 45.0.2454.101 m
![image](https://cloud.githubusercontent.com/assets/2529744/10323365/c34d3dc4-6c3f-11e5-98dd-d92d11ef1e56.png)

**Comment by SimeonC** [comment]
Weird, I'm on same version of chrome (Version 45.0.2454.101 (64-bit)) with a Retina Macbook pro and I get the following. Maybe this is one of those <1px rounding issues...
![image](https://cloud.githubusercontent.com/assets/1085899/10323408/5a3172a6-6cdf-11e5-816c-3f948370100f.png)

**Comment by SimeonC** [comment]
I'm actually considering changing away from rem back to px and % to avoid issues like this altogether (And some other weird problems I had on other sites).
