### ISSUE TITLE
Clicking on button in time-date-picker submits surrounding form (material)

### ISSUE THREAD

**Issue by Ventzy** [SimeonC/sc-date-time#15]
I have form tag and <time-date-picker> inside. time-date-picker uses md-button and md-button is rendered as button tag (https://material.angularjs.org/0.11.2/#/api/material.components.button/directive/mdButton). The template in scDateTime don't set the type of the button (like type="button"), then button tag is rendered without type and the default html behavior is to assume type="submit", which submits the form. This is not expected behavior - clicking on date in calendar submits the whole form. Probably type="button" should be added in the templates.

**Comment by SimeonC** [comment]
Nice catch! Sorry it took so long to respond - my email notifications broke.

**Comment by joshting** [comment]
Yup, got the same problem when trying to use sc-date-time in my form.
