### ISSUE TITLE
On-save callback doesn't work 

### ISSUE THREAD

**Issue by yigaldviri** [SimeonC/sc-date-time#17]
Hi, 
I have been trying to use the 'on-save' attribute and sending a callback function.
when i used: 

```
on-save="controller.saveCallBack($value)"
```

It evaluated to undefined in this part of your code:

```
saveFn = $parse(attrs.onSave);
```

And when i used: 

```
on-save="{{controller.saveCallBack($value)}}"
```

Your code evaluated it correctly but the function executed multiple times (something like 15 times) while the directive initiated. Furthermore, the callback called (twice) not only when clicking save but even when picking a new date.
So, am I doing something wrong?

**Comment by SimeonC** [comment]
Can you post up the full HTML of your setup, I'll have a look at my setup tomorrow and see if I can figure it out.

**Comment by yigaldviri** [comment]
Sorry, my bad.
I had 2 directives in one html and i mixed it up.
So sorry for the trouble. Thanks for all of your effort!
