### ISSUE TITLE
Support npm installation

### ISSUE THREAD

**Issue by zack9433** [SimeonC/sc-date-time#19]
Could you publish to npm registry?

**Comment by WuDo** [comment]
+1

**Comment by whoknows** [comment]
+1

**Comment by SimeonC** [comment]
I'll look into it, I've done it before so pretty sure I can do it again.

**Comment by shprink** [comment]
+1

**Comment by grawk** [comment]
+1

**Comment by vyrak** [comment]
+1...any updates on this?

**Comment by rhinoceraptor** [comment]
`sc-date-time` is on NPM but it does not appear to be packaged to be NPM compatible (e.g. working with Browserify/Webpack).

**Comment by grawk** [comment]
bump
