### ISSUE TITLE
Remove font-awesome dependency

### ISSUE THREAD

**Issue by jpike88** [SimeonC/sc-date-time#21]
That's overkill, there's no good reason for having that as a requirement, it's just more bloat.

**Comment by mrzepinski** [comment]
+1 It will be much simpler to use Material Icons - https://www.google.com/design/icons/

**Comment by SimeonC** [comment]
I guess it's an optional if you want to change the templates. As a default it's required for arrow and other calendar/clock icons.

No to material icons - they only really work in a material setting and this is not restricted to material (also material icons are a LOT more bloat than font-awesome).

I'm not changing this but if you want to use other icons you can just edit the templates then you don't have to include FA at all.
