### ISSUE TITLE
mindate & maxdate

### ISSUE THREAD

**Issue by will-break-it** [SimeonC/sc-date-time#22]
Hi, I am trying to set a mindate within the directive declaration, like this:
<time-date-picker name="start"
                                  mindate="{$ minDate $}"
                                  data-ng-model="example"
                                  data-ng-required="true"></time-date-picker>

My minDate variable is calculated through moment js before that. But I just can't make it work. The calendar does not really disable any day buttons. Thanks in advance.

**Comment by SimeonC** [comment]
Not sure but I think you mean to have `mindate="{{minDate}}"` ?
If you inspect element on the html it might make it more clear - mindate and maxdate are observed so all changes are picked up. Check the examples in the gh-pages fork as well.
If you're still having issues run up a plnkr or codepen or similar and I can have a look.
