### ISSUE TITLE
Month not shown complete

### ISSUE THREAD

**Issue by ghost** [SimeonC/sc-date-time#23]
![sc-date-time](https://cloud.githubusercontent.com/assets/12096703/11143995/99b583ea-89f9-11e5-93f2-9f3247f6c6d3.jpg)

I can only get this to show 4 weeks. Has anyone got an idea how to fix this?

**Comment by SimeonC** [comment]
That's a CSS issue - I'm thinking you're using angular-material?

We have another ticket which should hopefully fix this #14 but for now it looks like the height of the buttons isn't being overridden correctly - they should be circles not tall ovals. Run up a jsfiddle and I should be able to get you a CSS snippet to fix that if you can't figure it out yourself.

**Comment by ghost** [comment]
I am using angular-material. I have overridden the css height properties and now it is being shown correctly. It can also be that the line-height is wrong in my setup (hence the oval buttons).

**Comment by SimeonC** [comment]
Yea, the line-height and height have to be the same for that otherwise one overrides the other.
