### ISSUE TITLE
fullTitle should consider displayTwentyfour

### ISSUE THREAD

**Issue by pikooh** [SimeonC/sc-date-time#25]
I implemented the modal version, similar to the one in the demo (material). I've set the displayTwentyfour config to true, yet the fullTitle of the dialog contains the AM/PM value, since this is hardcoded. Could this be changed so that either the fullTitle is customizable or at least follows some of the settings?

**Comment by SimeonC** [comment]
That's an oversight on my part. I'll get it fixed when I can.
