### ISSUE TITLE
[FEAT] Clock mode

### ISSUE THREAD

**Issue by SimeonC** [SimeonC/sc-date-time#3]
Old Issue: https://github.com/SimeonC/md-date-time/issues/9
Abridged Summary

@amcdnl

> On one of your comments here angular/material#648 you show a clock picker. Personally I prefer that over the up down, is that still available?

@simeonc

> There's an older version of it here that has the clockface: http://codepen.io/SimeonC/pen/XJdWPy

@georgebarbarosie

> This one seems to be closest to the material design behavoiour http://weareoutman.github.io/clockpicker/ so I believe @amcdnl might have had it in mind.

@amcdnl

> Have you seen this? http://material-ui.com/#/components/time-picker

@simeonc

> I do like that way of doing hours/minutes, though it could do with a bit of work, the double layer on selecting hours is a little confusing.
> 
> If we take that option but show both the minute and hour hands, highlighting the hand you are selecting and showing either minutes or hours around the face I think that could work.
> 
> Common to all the implementations I've seen so far, that I want to figure some way around, is that "jump" you get when selecting an hour and it switches to minutes. That feels jarring to me.

Tagging old participants (Sorry for the spam): @georgebarbarosie @amcdnl

**Comment by sam2x** [comment]
Hi guys, nice project. Any news about clock interface mode ?
