### ISSUE TITLE
AutoSave Option 'True' doesn't work

### ISSUE THREAD

**Issue by osnaraus** [SimeonC/sc-date-time#30]
I can set up autosave option, That's all.

**Comment by stolbejj77** [comment]
Agreed it definitely doesn't work. I've been going crazy trying to test all different scenarios, and eventually cleared out all of my previous work and just went with the bare boned code, and I was unable to get the model to change when 'autosave' is set to true and the date is changed. The only thing that updates is the value of the calendar. Other inputs that are tied to the model tied to the calendar don't update at all.

**Comment by SimeonC** [comment]
Hey, I can't see any reason why this wouldn't be working. Could you run up a plnkr/codepen with the latest version so I can see the problem please?

**Comment by diegogurgel** [comment]
Auto save updates the model and on-save event is not fired. Ok?

**Comment by Knoxvillekm** [comment]
http://jsfiddle.net/Knoxvillekm/dmqvqwn0/

autosave doesn't change model values (or only once), only button "now" makes this

**Comment by JosMarRivera** [comment]
+1, autosave only works in the firts click, and onSave-onCancel doesn´t work.

**Comment by pattyjogal** [comment]
For the two above, when I use the {{ }} notation to call the model, the paragraph field is updated. Hope that helps!

Here's a fork of your fiddle: http://jsfiddle.net/8x6m10tg/

**Comment by JosMarRivera** [comment]
@pattyjogal Thank you very much! It can be useful to me.

**Comment by pattyjogal** [comment]
Glad I could help!

**Comment by psaunders** [comment]
I'm having this problem too, it seems to have problems if you have it tied to a model that isn't right on the root scope. So I have it in a controller where it is set to c.article.published_at and it's giving me trouble. It does work if you turn autosave off and make people click save, but if you're not using it as a modal I don't think users will expect they have to click save.

**Comment by tezqa** [comment]
A quick workaround, but you have to edit the directive's source code:

Replace these lines:

```
scope.saveUpdateDate = function() {
  return ngModel.$setViewValue(scope.date);
};
```

by:

```
scope.saveUpdateDate = function() {
  return ngModel.$setViewValue(new Date(scope.date));
};
```

**Comment by pesektomas** [comment]
@tezqa Nice, thenk you! Are there any reason which make it impossible for PR?

Thenk you again!

**Comment by minchopm** [comment]
if you make something like this 
scope.saveUpdateDate = function () {
            var saveFn = $parse(attrs.onSave);
            ngModel.$setViewValue(new Date(scope.date));
            saveFn(scope.$parent, {$value: new Date(scope.date)});
            return ngModel.$setViewValue(scope.date);
          };
          return scope.autosave = true;

it will trigger on save properly with autosave=true
