### ISSUE TITLE
Popup version does not work.

### ISSUE THREAD

**Issue by ealione** [SimeonC/sc-date-time#36]
Trying to add something like this in my own local test does not produce the popover as shown in the demo.

<input class="form-control ng-invalid ng-invalid-max ng-touched ng-dirty" type="text" name="dateOfBirth" ng-model="date" placeholder="Date of Birth" date-time-picker-input="" display-mode="date" display-format="d MMMM yyyy" aria-invalid="true" style="">

Even in the material demo page though, if you click cancel, the calendar wont pop up again anymore.

**Comment by pradt** [comment]
I have the same issue as well. Exactly what you have stated.

**Comment by SalmanZafar214** [comment]
same here i cant make it work using Popup version

**Comment by gabrielAnzaldo** [comment]
same issue here.

**Comment by Larmen** [comment]
I think I've figured this out, hopefully this helps someone (although I'm sure all of you other commenters have picked something else a long time ago):
You need to copy the directives from the extra files loaded - so for Bootstrap for example the directives are in this file http://simeonc.github.io/sc-date-time/javascripts/bootstrap.js
These directives have a dependency to AngularStrap which is loaded from here in the demo files https://cdnjs.cloudflare.com/ajax/libs/angular-strap/2.3.3/angular-strap.min.js
