### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by enieber** [SimeonC/sc-date-time#38]
I'm trying to use this lib, but I could not quite understand the documentation. My suggestion is to be made a demo code as was done in [md-date-time](http://codepen.io/SimeonC/pen/XJdWPy).

**Comment by enieber** [comment]
It could be the own wiki project

**Comment by SimeonC** [comment]
There are demo codes available on the gh-pages branch https://github.com/SimeonC/sc-date-time/tree/gh-pages - the running code can be seen at http://simeonc.github.io/sc-date-time.

Will that do?

**Comment by enieber** [comment]
no, would be the code bootstrap and material demo

**Comment by SimeonC** [comment]
Try looking in the bootstrap.html and material.html files?

**Comment by thelordgabo** [comment]
Hi all, does someone knows how to use the component as a modal? I did not found any example.

**Comment by pinzonjulian** [comment]
Hi, I'm also having issues trying to understand how to use the material version. 
It would be very useful to show code examples alongside the working demos.
