### ISSUE TITLE
I can't see anything displayed aside from the title div and footer div

### ISSUE THREAD

**Issue by griff4692** [SimeonC/sc-date-time#39]
There html inside of the following tag: <div ng-click="modeSwitch()" aria-label="Switch to Calendar" class="display" role="button"   tabindex="0"><div class="title ng-binding">January 21 2016</div><div class="content"><div   class="super-title ng-binding"></div><div ng-bind-html="display.main()" class="main-title ng-binding">10:20<small>PM</small></div><div class="sub-title ng-binding">22:20</div></div></div>

Is rendered in the browser but hidden from view (all I see is a green header and footer).

**Comment by SimeonC** [comment]
Check your CSS, likely something in a parent element is overriding the text color.

**Comment by griff4692** [comment]
If it is a parent container, how could it be overriding ?

Is there a way I can ensure the color using jquery.  A certain div and I
can $ css "color" black or something?

**Comment by SimeonC** [comment]
If a !important has been defined that might do it. Try open the chrome inspector on the picket and see what's happening. If you can replicate it in a plunkr or similar I can probably spot the issue.
