### ISSUE TITLE
Support for selecting multiple dates

### ISSUE THREAD

**Issue by yoanisgil** [SimeonC/sc-date-time#42]
Hi,

I was wondering if is it possible to add support for selecting multiple dates? I'm working on a project where I need to implement such a feature and I'm already using sc-date-time.

If time is a constraint I could take a look myself and try to implement but I wanted to check first if it's doable with the current state of the project  and if it will be a desirable feature.

Bests,

Yoanis.

**Comment by simkepal** [comment]
Hi, 

I would also need this. If anyone will be working on this please let us know.

Thank you!

Simon

**Comment by jrencz** [comment]
:+1:
