### ISSUE TITLE
Manually entering date and time?

### ISSUE THREAD

**Issue by rvarbanov** [SimeonC/sc-date-time#49]
Hi, I could not tell from your demo page if I could manually enter date and time with the keyboard instead of the dialog?

**Comment by mebibou** [comment]
what about opening the datetime picker from a click on a button next to the input and letting the user enter what he wants in the input?

**Comment by HGXXL** [comment]
It is possible for the time to edit it manually, see: http://simeonc.github.io/sc-date-time/material.html
