### ISSUE TITLE
[BUG] displayMode isn't overriding defaultMode

### ISSUE THREAD

**Issue by ryananthonydrake** [SimeonC/sc-date-time#5]
displayMode: 'time' isn't overriding the defaultMode, though your README says it should be.

```
 defaultMode: 'date',
  defaultDate: void 0,
  displayMode: 'time',
```

![Uploading Screen Shot 2015-09-16 at 2.22.11 pm.png…]()

**Comment by SimeonC** [comment]
Hmmm, I can't replicate that. Can you run up a plunkr or similar to demonstrate it?
Do note that anything set on the element itself overrides the config settings.
