### ISSUE TITLE
Open date/time picker in a dialog?

### ISSUE THREAD

**Issue by rvarbanov** [SimeonC/sc-date-time#50]
I could not tell from your demo if you could open the picker in a dialog? (Current version of Angular Material does not support dialog in dialog action v1.0.6)

**Comment by lacvapps** [comment]
I have it working ins a dialog using a custom html file

**Comment by langdonx** [comment]
I've got it working in `$mdDialog`, but it's a little janky.  Content shifts with or without `ng-cloak` if you try to use `display-mode="full"`, and it seems like you're forced to use their buttons (and not standard `mdDialog` buttons).
