### ISSUE TITLE
[FEAT] Increase / decrease minutes by every 15mins

### ISSUE THREAD

**Issue by mebibou** [SimeonC/sc-date-time#51]
It would be nice to have the possibility to define how many minutes are being changed when you click once on the arrow up/down of the time picker, i.e. if the picker opens with 3.00pm, then I can only change to 2.45pm, 3.15pm, 3.30pm, etc.

**Comment by pattyjogal** [comment]
Very good point. If anyone is looking for a short term solution, changing the calls of `clock._incMinutes(±1)` to `clock._incMinutes(±15)` works with a little hacking.
