### ISSUE TITLE
sc-date-time on npm

### ISSUE THREAD

**Issue by xileftenurb** [SimeonC/sc-date-time#56]
Hello,

with some research, I found [this](https://www.npmjs.com/package/sc-date-time) npm package.

I wondered why is there is no documentation about it in the readme? It would be simple and really appreciated to add some documentation, and it would help other to find the package for those who don't use bower.

thank you

**Comment by graingert** [comment]
@xileftenurb it looks like @PillowPillow published it because @SimeonC forgot to?

**Comment by PillowPillow** [comment]
@graingert's right, i can remove the package from npm if @SimeonC want to publish his own.

**Comment by graingert** [comment]
@PillowPillow I'm working on a fork https://www.npmjs.com/package/md-date-time
