### ISSUE TITLE
[DEMO] Dropdown

### ISSUE THREAD

**Issue by amcdnl** [SimeonC/sc-date-time#6]
Per https://github.com/SimeonC/md-date-time/issues/12, lets add a implementation that shows a dropdown with a input box similar to ui-bootstraps popup demonstration. https://angular-ui.github.io/bootstrap/#/datepicker

**Comment by SimeonC** [comment]
I agree, this is a good idea. Also need a popup demo in material side of things too.

**Comment by ryananthonydrake** [comment]
+1

**Comment by SimeonC** [comment]
To tide you all over until I manage to get this setup properly I've created a gist of my Bootstrap version here https://gist.github.com/SimeonC/7e0b5d6cae1c79deb48d

**Comment by SimeonC** [comment]
Ok, site has been updated, I have demo's for Bootstrap popover and modal. Also there is a demo with angular-material's modal. They're up on the github pages site.

**Comment by amcdnl** [comment]
@SimeonC ran into a couple of issues:
1. If I open it from either material or bootstrap after the first time i select and close it doesn't open again.
2. There is no way to close it in bootstrap besides clicking the box again ( odd ).  I'd suggest clicking outside the box have it close the dropdown and a cancel button.
3. If I change the input box value, the calendar does not update.

**Comment by SimeonC** [comment]
Yea, I know about most of them - except the first one. The dropdown one is a bit funny and possibly I'd use a different dropdown plugin, I figured better to get them up then fix them later as I was having lots of trouble getting them to work correctly. I'll have another look at it later.

**Comment by sam2x** [comment]
Hey i don't find the demo with modal/input on-click ? i actually want to use sc-date-time so it's showing-up onclick for mobile integration.

**Comment by SimeonC** [comment]
Try clicking on the first input of the bootstrap or material demo pages. It's a bit rough but works as a demo.

**Comment by gabrielAnzaldo** [comment]
Can you help me please, I can not have the modal form working.

**Comment by morganRotaStabelli** [comment]
I need that beautiful date/timepicker in a modal-form , but as soon as I click in the input the $mdDialog.show() replaces the form dialog with his own modal... 
How can I resolve it? Showing/hiding a div with the calendar positoned absolutly "aping" the modal behaviour seems a bad solution, or not?

**Comment by amritk** [comment]
@morganRotaStabelli look into passing skip_hide = true into your alerts
![screen shot 2016-09-12 at 5 07 10 pm](https://cloud.githubusercontent.com/assets/2039539/18457190/72261612-790b-11e6-87ed-cf6708b965a5.png)
