### ISSUE TITLE
Font awesome dependency

### ISSUE THREAD

**Issue by instantaphex** [SimeonC/sc-date-time#61]
Because this is for bootstrap and angular material, it would be much better to use glyphicons and material icons as opposed to font awesome icons.  I actually can't find anywhere where font awesome is listed as a dependency.

**Comment by amritk** [comment]
yep, if you edit the template you can use whichever icons you want

**Comment by instantaphex** [comment]
Yeah that's what I did but the template is supposed to be for material and
it only works if you either edit it or use bootstrap along with material.

**Comment by boyum** [comment]
As FA uses the SIL OFL license (https://tldrlegal.com/license/open-font-license-(ofl)-explained), why not use SVG versions of the few that are needed, and get rid of the entire dependency once and for all? 

If I've misunderstood the license, forget everything I've said.
