### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by graingert** [SimeonC/sc-date-time#63]
@SimeonC the last commit to this repo was back in 2015, the npm project is owned by someone else, and there are many unanswered PRs and issues. Is this project to be considered unmaintained?

**Comment by SimeonC** [comment]
Yes, it is unmaintaned. We were using it at my last company and I was supposed to get some time from them to maintain it (the usual we support open source spiel - i.e. We want to use free software). Now I've moved to working in React and also I left the company.

**Comment by SimeonC** [comment]
If you want I can hand over the project if you want to keep working on it?

**Comment by graingert** [comment]
Cool, thanks for the offer! I'll finish of the changes I need in
md-date-time and if/when that gets integrated and tested in my app I'll be
happy to take this project over.

**Comment by graingert** [comment]
@SimeonC yup my new changes in md-date-time work for me. I'm happy to take this over, and the npm repo from @PillowPillow

**Comment by PillowPillow** [comment]
It seems that i can't remove the repo because it's older than 24h. @graingert , I added you as collaborator so you can update the repo with your latest changes.

**Comment by graingert** [comment]
@PillowPillow I wouldn't want to remove it anyway.

**Comment by graingert** [comment]
@SimeonC I need to be able to configure travis for tests and bower builds, could you move the project to https://github.com/sc-date-time ?

**Comment by graingert** [comment]
@SimeonC I've added you as an owner there too, so if you accept the invite you'll keep all the permissions you have here.

**Comment by SimeonC** [comment]
Done! Thanks for taking it over.
