### ISSUE TITLE
Popup version

### ISSUE THREAD

**Issue by amritk** [SimeonC/sc-date-time#7]
Has anyone created a popup version to use on mobile? I tried throwing it into an mdcustomdialog but it doesn't quite fit.

**Comment by SimeonC** [comment]
Am closing this as there's already a request for this in #6 (I'll add a note).

For now you can try use the new compact setting which removes the left side and makes the whole thing a bit smaller until I can get the time to create a demo.

**Comment by amritk** [comment]
sweet thanks
